# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"add": "00_core.ipynb",
         "multiply": "00_core.ipynb",
         "subtract": "00_core.ipynb",
         "divide": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://alinaselega.github.io/nbdev_calc/"

git_url = "https://github.com/alinaselega/nbdev_calc/tree/master/"

def custom_doc_links(name): return None
