# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['add', 'multiply', 'subtract', 'divide']

# Cell
def add(x, y):
    "Add x and y"
    return x+y

def multiply(x, y):
    "Multiply x and y"
    return x*y

def subtract(x, y):
    "Subtract y from x"
    return add(x, -y)

def divide(x, y):
    "Divide x by y"
    return x/y